"""
Prompt builder: converts OpenAI message list into a single Codex prompt string.

Format (per PDF skeleton):
    Role:\\n<content>\\n\\nRole:\\n<content>\\n\\nAssistant:\\n

Rules:
  - Image content parts are already rejected upstream (chat_request.py validator).
    If a list of TextContent arrives here, concatenate text fields only.
  - Total length is capped at ``settings.CHAT_MAX_PROMPT_CHARS``; raises
    ``ValueError`` which the route handler converts to a 400.
  - System, user, assistant all get their role capitalised as the header.
  - role=tool messages are formatted as "Tool <name> result: <content>".
  - role=assistant messages with tool_calls are formatted as calls summary.
  - An optional tools_prompt string can be prepended as a leading System block
    to inject tool availability instructions into Codex's context.
"""

from __future__ import annotations

from typing import Any

from src.chat.tool_calling import (
    format_assistant_tool_call_for_prompt,
    format_tool_result_for_prompt,
)
from src.gateway.schemas.chat_request import Message, TextContent
from src.settings import get_settings


def build_prompt(
    messages: list[Message],
    tools_prompt: str | None = None,
) -> str:
    """Convert a list of chat messages into a single text prompt for Codex.

    Args:
        messages:     Validated list of Message objects (image parts already rejected).
        tools_prompt: Optional system-level tools instruction block generated by
                      ``format_tools_prompt``. When provided, it is prepended as
                      a System section before all other messages.

    Returns:
        Formatted multi-turn prompt string ending with ``Assistant:\\n``.

    Raises:
        ValueError: If the assembled prompt exceeds ``CHAT_MAX_PROMPT_CHARS``.
    """
    parts: list[str] = []

    # Prepend tools instructions as a leading System block when present.
    if tools_prompt:
        parts.append(f"System:\n{tools_prompt}")

    # Build a map from tool_call_id → tool name for resolving role=tool messages.
    # Populated as we iterate so we can look up names when the tool result arrives.
    tool_call_id_to_name: dict[str, str] = {}

    for msg in messages:
        # ── role=tool (tool result from client after assistant called a tool) ──
        if msg.role == "tool":
            tool_msg: dict[str, Any] = {
                "role": "tool",
                "tool_call_id": msg.tool_call_id or "",
                "content": _extract_text(msg),
                "name": msg.name,
            }
            parts.append(format_tool_result_for_prompt(tool_msg, tool_call_id_to_name))
            continue

        # ── role=assistant with tool_calls (history replay) ──
        if msg.role == "assistant" and msg.tool_calls:
            # Update the id→name map for any subsequent role=tool messages.
            for call in msg.tool_calls:
                if isinstance(call, dict):
                    call_id = call.get("id", "")
                    fn = call.get("function", {})
                    fn_name = fn.get("name", "") if isinstance(fn, dict) else ""
                    if call_id and fn_name:
                        tool_call_id_to_name[call_id] = fn_name

            # Build opaque dict for formatter — Any-typed to avoid content union issues
            msg_dict: dict[str, Any] = {
                "role": "assistant",
                "tool_calls": msg.tool_calls,
                "content": _extract_text(msg),
            }
            parts.append(format_assistant_tool_call_for_prompt(msg_dict))
            continue

        # ── Standard roles: system / user / assistant (no tool_calls) ──
        text = _extract_text(msg)
        parts.append(f"{msg.role.capitalize()}:\n{text}")

    prompt = "\n\n".join(parts) + "\n\nAssistant:\n"

    max_chars = get_settings().chat_max_prompt_chars
    if len(prompt) > max_chars:
        raise ValueError(
            f"prompt exceeds maximum length of {max_chars} characters " f"(got {len(prompt)})"
        )

    return prompt


def _extract_text(msg: Message) -> str:
    """Extract plain text from a message's content field."""
    if isinstance(msg.content, list):
        # Only TextContent parts arrive here (ImageContent rejected by validator).
        return "".join(part.text for part in msg.content if isinstance(part, TextContent))
    return msg.content or ""
